window.__JOBS__ = {
  "idraulica": [
    "Riparare un rubinetto che perde",
    "Sostituire una guarnizione del rubinetto",
    "Sbloccare uno scarico intasato del lavandino",
    "Sbloccare il WC intasato",
    "Sostituire il sifone del lavandino",
    "Cambiare la cartuccia del miscelatore",
    "Sostituire il flessibile della doccia",
    "Riparare una perdita da un tubo sotto il lavandino",
    "Sostituire il galleggiante dello sciacquone",
    "Installare un nuovo rubinetto della cucina",
    "Sostituire il soffione della doccia",
    "Eliminare cattivi odori dagli scarichi",
    "Sostituire un tubo flessibile del gas",
    "Regolare la pressione dell'acqua in casa",
    "Sostituire una valvola di non ritorno",
    "Installare un addolcitore d'acqua sotto lavello",
    "Riparare una perdita dal termosifone",
    "Spurgare l'aria dai termosifoni",
    "Sostituire il pulsante dello sciacquone",
    "Riparare una perdita alla base del WC",
    "Sostituire un tubo corrugato flessibile",
    "Installare un filtro anticalcare",
    "Pulire il filtro dell'acqua in ingresso",
    "Sostituire una guarnizione della lavatrice",
    "Collegare lo scarico della lavastoviglie",
    "Sostituire un raccordo che perde",
    "Isolare un tubo dell'acqua dal gelo",
    "Sostituire una valvola di sicurezza dello scaldabagno",
    "Svuotare e pulire uno scaldabagno elettrico",
    "Sostituire l'anodo di sacrificio dello scaldabagno",
    "Installare un rubinetto a sfera di intercettazione",
    "Sostituire un flessibile del WC",
    "Riparare una cassetta di scarico incassata",
    "Installare un rubinetto esterno da giardino",
    "Installare un miscelatore termostatico per la doccia",
    "Sostituire una colonna doccia completa",
    "Installare uno scaldabagno istantaneo elettrico",
    "Sostituire il gruppo di scarico di una vasca",
    "Installare un piatto doccia con scarico a pavimento",
    "Sostituire un tubo in PVC di scarico",
    "Collegare un frigorifero con dispenser d'acqua",
    "Installare un depuratore d'acqua sotto lavello",
    "Sostituire una pompa di circolazione del riscaldamento",
    "Bilanciare l'impianto di riscaldamento a più radiatori",
    "Sostituire una valvola termostatica del radiatore",
    "Installare un contatore d'acqua divisionale",
    "Riparare una perdita in una tubazione esterna interrata",
    "Installare un sistema di raccolta dell'acqua piovana",
    "Collegare una lavastoviglie a incasso",
    "Installare un addolcitore d'acqua centralizzato",
    "Riparare una perdita in una giunzione filettata",
    "Sostituire un tubo flessibile ad alta pressione",
    "Installare un rubinetto a doppia via per lavatrice e lavastoviglie",
    "Sostituire una pompa di sollevamento per acque reflue",
    "Installare un sistema di irrigazione da esterno collegato alla rete idrica",
    "Sostituire una guarnizione toroidale (O-ring) di un rubinetto",
    "Installare un misuratore di portata sull'impianto",
    "Sostituire un'elettrovalvola dell'impianto di irrigazione",
    "Isolare termicamente le tubazioni del riscaldamento in cantina",
    "Sostituire un sifone a bottiglia con uno a S",
    "Installare un rompigetto anticalcare sui rubinetti",
    "Sostituire una pompa sommersa da pozzo",
    "Riparare una perdita su un collettore di distribuzione",
    "Installare un vaso di espansione sull'impianto termico",
    "Sostituire una valvola di sfiato automatica",
    "Installare un manometro per monitorare la pressione dell'impianto",
    "Riparare una crepa in una vasca in resina",
    "Installare un bidet sospeso",
    "Sostituire un WC tradizionale con uno sospeso",
    "Installare un sistema di scarico a parete con cassetta incassata",
    "Sostituire tutte le guarnizioni di un rubinetto vecchio",
    "Installare un rubinetto filtrante per acqua da bere",
    "Sostituire un tubo in rame con raccordi a pressare",
    "Diagnosticare la causa di un calo di pressione in tutta la casa",
    "Installare uno scambiatore di calore per un impianto misto",
    "Sostituire una pompa di calore split (solo collegamento idraulico base)",
    "Progettare la disposizione degli scarichi per un bagno nuovo",
    "Collaudare un impianto idraulico dopo una ristrutturazione",
    "Sostituire completamente i collegamenti idraulici di una cucina",
    "Installare un sistema di osmosi inversa sotto lavello",
    "Riparare un impianto misto caldo/freddo con perdita nascosta",
    "Sostituire un tubo di scarico rotto sotto il pavimento",
    "Installare un rubinetto a incasso da parete",
    "Sostituire una guarnizione a labbro di un rubinetto moderno",
    "Riparare un blocco idraulico del piano cottura a gas",
    "Sostituire una colonna di scarico verticale condominiale (parte propria)",
    "Installare un misuratore di consumo acqua smart",
    "Sostituire una pompa booster per aumentare la pressione",
    "Riparare un raccordo del contatore del gas che perde (solo segnalazione, non intervento diretto)",
    "Installare un sifone salvaspazio per mobili bagno sospesi",
    "Sostituire una vasca da bagno con doccia walk-in",
    "Installare un sistema di ricircolo acqua calda sanitaria",
    "Sostituire un tubo in multistrato con raccordi a pressare",
    "Riparare un allacciamento idraulico esterno danneggiato dal gelo",
    "Installare un depuratore d'acqua a osmosi con rubinetto dedicato",
    "Sostituire un pozzetto di scarico intasato in giardino",
    "Installare un impianto di scarico per una cucina esterna",
    "Sostituire una guarnizione della caldaia a condensazione",
    "Riparare una perdita nella serpentina di uno scambiatore",
    "Installare un vaso di espansione sanitario",
    "Sostituire un dispositivo anti-legionella su un boiler"
  ],
  "elettricita": [
    "Sostituire una spina a un cavo",
    "Sostituire un interruttore della luce",
    "Sostituire una presa elettrica",
    "Installare una plafoniera al soffitto",
    "Sostituire una lampadina con attacco particolare",
    "Aggiungere una presa USB a muro",
    "Collegare un lampadario nuovo",
    "Sostituire il cavo di un elettrodomestico",
    "Installare un rilevatore di fumo",
    "Installare una presa con interruttore",
    "Collegare una lavatrice nuova alla rete elettrica",
    "Installare un sensore di movimento per le luci",
    "Sostituire un citofono",
    "Aggiungere una ciabatta fissa a muro",
    "Capire quale cavo serve per un elettrodomestico",
    "Verificare se una presa è a norma",
    "Sostituire un deviatore per accendere una luce da due punti",
    "Installare un dimmer per regolare l'intensità della luce",
    "Sostituire una presa Schuko con una presa italiana",
    "Installare una presa esterna per il giardino",
    "Collegare un condizionatore portatile alla rete elettrica",
    "Sostituire il vetro di una plafoniera rotta",
    "Installare strisce LED sotto i pensili della cucina",
    "Verificare perché un interruttore differenziale scatta spesso",
    "Sostituire una campanella del citofono",
    "Installare una presa per la lavastoviglie",
    "Collegare un forno elettrico da incasso",
    "Sostituire un magnetotermico nel quadro elettrico",
    "Installare un videocitofono al posto del citofono tradizionale",
    "Sostituire un faretto da incasso a soffitto",
    "Installare un ventilatore da soffitto con telecomando",
    "Aggiungere una linea dedicata per il forno a microonde",
    "Sostituire un salvavita (differenziale) nel quadro",
    "Installare prese multiple in una parete attrezzata",
    "Collegare un climatizzatore fisso (solo parte elettrica)",
    "Sostituire un trasformatore per faretti a bassissima tensione",
    "Installare un sistema di illuminazione smart con app",
    "Aggiungere un punto luce in un ripostiglio",
    "Sostituire una presa da incasso danneggiata",
    "Installare una presa dedicata per la ricarica auto elettrica",
    "Verificare il corretto collegamento a terra dell'impianto",
    "Sostituire un quadro elettrico vecchio con uno a norma",
    "Installare un contattore per l'irrigazione automatica",
    "Aggiungere un punto luce esterno con sensore crepuscolare",
    "Sostituire i cavi di un lampadario a più bracci",
    "Installare un termostato smart per il riscaldamento",
    "Collegare un allarme antifurto cablato",
    "Sostituire una presa TV/antenna",
    "Installare un punto di rete Ethernet a muro",
    "Aggiungere una presa dati per il router",
    "Sostituire l'impianto elettrico di una singola stanza",
    "Installare un impianto di illuminazione a binario",
    "Sostituire un fusibile in un impianto datato",
    "Installare un rilevatore di gas metano",
    "Collegare un piano cottura a induzione (solo parte elettrica)",
    "Sostituire l'interruttore generale dell'impianto",
    "Installare un sistema di prese comandate da telecomando",
    "Aggiungere un differenziale dedicato per il bagno",
    "Sostituire un cavo elettrico danneggiato sotto traccia",
    "Installare un impianto fotovoltaico domestico (solo assistenza base)",
    "Collegare una pompa di calore (solo parte elettrica)",
    "Installare un caricabatterie da muro per dispositivi",
    "Sostituire una scatola di derivazione danneggiata",
    "Verificare un guasto intermittente su un circuito luci",
    "Installare un impianto citofonico multi-appartamento",
    "Sostituire cavi non a norma con cavi certificati",
    "Aggiungere un punto presa in mansarda",
    "Installare un sistema di domotica per tapparelle elettriche",
    "Sostituire un motore per tapparella elettrica",
    "Collegare un caricatore wireless da incasso nel mobile",
    "Installare un impianto di allarme wireless",
    "Sostituire il contatore con uno digitale (assistenza, non allaccio ufficiale)",
    "Aggiungere una presa stagna per esterno",
    "Installare un impianto di illuminazione da giardino a bassa tensione",
    "Sostituire il cablaggio di un impianto stereo multi-stanza",
    "Verificare e sistemare un impianto dopo un allagamento",
    "Installare prese USB-C ad alta potenza per ricarica rapida",
    "Progettare la disposizione punti luce per una ristrutturazione",
    "Collaudare un impianto elettrico dopo lavori importanti",
    "Sostituire completamente l'impianto elettrico di un piccolo appartamento",
    "Installare un sistema di monitoraggio energetico domestico",
    "Sostituire una presa industriale trifase (con cautela)",
    "Installare un impianto di illuminazione per un giardino d'inverno",
    "Sostituire un dimmer touch per LED",
    "Collegare una pompa di calore aria-acqua (solo parte elettrica base)",
    "Installare un sistema di videosorveglianza cablato",
    "Sostituire un cavo coassiale per l'antenna TV",
    "Installare un punto luce per un lampadario a soffitto alto",
    "Sostituire una presa per forno a doppia potenza",
    "Installare un impianto di ricarica per bici elettrica",
    "Collegare un gruppo di continuità (UPS) per il computer",
    "Sostituire un rilevatore di CO (monossido di carbonio)",
    "Installare un sistema di controllo accessi con badge",
    "Sostituire una plafoniera a LED con sensore di movimento integrato",
    "Installare un quadro elettrico ausiliario per un garage",
    "Sostituire una presa per la ricarica di attrezzi da giardino",
    "Installare un contatore energetico per un impianto fotovoltaico",
    "Collegare una centralina domotica per il controllo luci",
    "Sostituire un interruttore crepuscolare per l'illuminazione esterna",
    "Installare un sistema di illuminazione di emergenza",
    "Sostituire completamente il cablaggio elettrico di una mansarda"
  ],
  "falegnameria": [
    "Montare un mobile IKEA",
    "Riparare una porta che gratta contro il pavimento",
    "Sostituire una cerniera della porta",
    "Regolare le ante di un armadio",
    "Installare una mensola a muro",
    "Riparare un cassetto che si inceppa",
    "Sostituire una maniglia della porta",
    "Montare una zanzariera",
    "Riparare una sedia traballante",
    "Costruire una semplice libreria",
    "Sostituire la serratura di una porta interna",
    "Livellare un mobile su pavimento irregolare",
    "Riparare uno spigolo scheggiato del legno",
    "Montare un'anta a battente",
    "Fissare un quadro pesante a muro",
    "Sostituire le guide di un cassetto",
    "Riparare una tavola di legno spaccata",
    "Montare una porta scorrevole",
    "Sostituire il vetro di una porta interna",
    "Costruire una pedana di legno per esterni",
    "Verniciare una porta in legno",
    "Sostituire i piedini di un mobile",
    "Riparare una persiana in legno",
    "Montare zoccolo battiscopa",
    "Costruire una piccola cassapanca",
    "Sostituire una tavola del parquet danneggiata",
    "Levigare e riverniciare un pavimento in legno",
    "Costruire una testiera per il letto",
    "Montare un tavolo da giardino in legno",
    "Riparare un telaio di finestra in legno",
    "Sostituire i cardini di un cancello in legno",
    "Costruire scaffali a muro su misura",
    "Montare un'anta scorrevole per armadio a muro",
    "Sostituire il piano di un tavolo danneggiato",
    "Costruire una struttura per un letto matrimoniale",
    "Riparare una scala in legno che scricchiola",
    "Montare un rivestimento a doghe di legno su una parete",
    "Costruire una cuccia da esterno per cani",
    "Sostituire i profili di tenuta di una porta-finestra",
    "Montare un controsoffitto in legno",
    "Costruire un tavolo da esterno con panche",
    "Riparare un telaio di porta danneggiato dall'umidità",
    "Sostituire completamente una porta interna con telaio",
    "Costruire una struttura a soppalco in legno",
    "Montare pannelli acustici in legno su una parete",
    "Riparare un mobile antico mantenendo la finitura originale",
    "Costruire una recinzione in legno da giardino",
    "Montare una veranda in legno prefabbricata",
    "Sostituire un architrave in legno di una porta",
    "Costruire una cabina armadio su misura",
    "Realizzare intarsi decorativi su un mobile",
    "Costruire scale interne in legno (progetto complesso)",
    "Sostituire un architrave in legno danneggiato",
    "Costruire una panca contenitore per l'ingresso",
    "Montare un cancelletto di sicurezza per bambini",
    "Riparare una gamba di tavolo spaccata",
    "Costruire un porta-riviste da parete",
    "Sostituire i binari di una tenda scorrevole",
    "Montare un'anta a soffietto per armadio",
    "Costruire una mensola galleggiante nascosta",
    "Riparare un tavolo con incastri allentati",
    "Costruire un porta-scarpe da ingresso",
    "Sostituire il piano di una scrivania",
    "Montare un separè in legno per ambienti",
    "Costruire una struttura per amaca da giardino",
    "Riparare i gradini di una scala in legno",
    "Costruire un tavolino da salotto su misura",
    "Montare pannelli decorativi 3D in legno",
    "Sostituire le doghe di una rete a doghe rotta",
    "Costruire una struttura per vasca da bagno in legno",
    "Riparare una finestra con telaio deformato",
    "Costruire un porta-biciclette da parete",
    "Montare un rivestimento in legno per una scala",
    "Costruire una struttura per un dondolo da giardino",
    "Riparare i cassetti di una cucina in muratura",
    "Costruire un tavolo da lavoro per garage",
    "Montare un armadio a ponte sopra il letto",
    "Costruire una struttura per zanzariera plissettata",
    "Riparare i cardini di un'anta pesante",
    "Costruire un porta-attrezzi da parete per garage",
    "Montare un pavimento in legno sopraelevato per esterno",
    "Costruire una porta a soffietto su misura",
    "Sostituire il piano di lavoro di una cucina in legno",
    "Riparare un infisso in legno con marcescenza localizzata",
    "Costruire una struttura per un letto a baldacchino",
    "Montare boiserie decorativa su una parete",
    "Sostituire le assi di un pavimento in legno esterno (decking)",
    "Costruire un porticato in legno lamellare",
    "Riparare una scala a chiocciola in legno",
    "Costruire un mobile su misura per un angolo irregolare",
    "Montare una copertura in legno per un pozzo decorativo",
    "Sostituire un davanzale in legno deteriorato",
    "Costruire una struttura per altalena da giardino",
    "Riparare i gradini esterni in legno di una veranda",
    "Costruire un rivestimento a cassettoni per un soffitto",
    "Montare un sistema di ante a scomparsa per una cabina armadio",
    "Sostituire completamente un pavimento in legno massello",
    "Costruire una recinzione decorativa con intagli",
    "Riparare una struttura portante di una tettoia in legno",
    "Costruire un tavolo da lavoro pieghevole per garage",
    "Montare un rivestimento in legno per una vasca da bagno freestanding"
  ],
  "muratura": [
    "Tinteggiare una stanza",
    "Riparare una crepa nel muro",
    "Stuccare un buco nel muro dopo aver tolto un chiodo",
    "Applicare la carta da parati",
    "Rifare la fuga delle piastrelle del bagno",
    "Sostituire una piastrella rotta",
    "Tinteggiare un soffitto",
    "Applicare pittura antimuffa in bagno",
    "Sigillare le fessure attorno agli infissi",
    "Verniciare un termosifone",
    "Applicare silicone attorno al lavandino o vasca",
    "Riparare l'intonaco scrostato",
    "Dipingere una parete con effetto decorativo semplice",
    "Rimuovere la muffa dal muro",
    "Fissare un tassello a muro forato",
    "Livellare un pavimento con autolivellante",
    "Sostituire una piastrella scheggiata",
    "Rasare una parete prima di dipingere",
    "Applicare una guaina impermeabilizzante",
    "Sigillare le fughe di un balcone",
    "Posare piastrelle in un bagno di piccole dimensioni",
    "Realizzare una parete divisoria in cartongesso",
    "Isolare una parete esterna con pannelli termici",
    "Rifare l'intonaco di una stanza intera",
    "Costruire un controsoffitto in cartongesso",
    "Realizzare una nicchia decorativa in cartongesso",
    "Posare un pavimento in laminato flottante",
    "Impermeabilizzare un terrazzo",
    "Rifare la pavimentazione esterna con autobloccanti",
    "Costruire un piccolo muretto divisorio in giardino",
    "Realizzare una parete in mattoni a vista decorativa",
    "Applicare rivestimento a cappotto termico esterno",
    "Sistemare crepe strutturali (valutazione e primo intervento)",
    "Realizzare una scala esterna in cemento",
    "Costruire un barbecue in muratura",
    "Ristrutturare completamente un bagno (progetto generale)",
    "Realizzare una vasca da giardino in cemento",
    "Costruire un piccolo forno a legna in muratura",
    "Rifare il massetto di un pavimento",
    "Realizzare una tettoia in muratura per l'auto",
    "Realizzare una nicchia per la TV nel muro",
    "Sostituire il pavimento del bagno con piastrelle nuove",
    "Costruire un gradino d'ingresso in cemento",
    "Realizzare un rivestimento in pietra per una parete",
    "Sistemare una grondaia distaccata dal muro",
    "Impermeabilizzare una cantina umida",
    "Costruire un'aiuola perimetrale in mattoni",
    "Realizzare una parete divisoria in blocchi di cemento",
    "Sostituire il rivestimento esterno di un balcone",
    "Costruire una base in cemento per un gazebo",
    "Riparare un cornicione esterno danneggiato",
    "Realizzare un pavimento in resina per garage",
    "Costruire una vasca per pesci in muratura da giardino",
    "Sistemare le fughe di un pavimento esterno",
    "Realizzare un rivestimento a intonaco decorativo veneziano",
    "Costruire un piccolo ripostiglio esterno in muratura",
    "Riparare crepe da assestamento in una parete portante (valutazione)",
    "Realizzare una canna fumaria in muratura",
    "Costruire una recinzione in blocchi e intonaco",
    "Ristrutturare un pavimento storico in cotto",
    "Realizzare un camino decorativo in muratura",
    "Costruire un pozzo decorativo da giardino",
    "Sistemare l'intonaco di una facciata esterna",
    "Realizzare gradini esterni in pietra naturale",
    "Costruire un muretto a secco decorativo",
    "Riparare una grondaia in cemento danneggiata",
    "Realizzare una base in cemento per un capanno",
    "Sostituire il pavimento di un balcone",
    "Costruire un caminetto esterno decorativo",
    "Riparare un tratto di marciapiede in cemento",
    "Realizzare un rivestimento in klinker per una facciata",
    "Costruire una fontana decorativa in muratura",
    "Sistemare l'intonaco interno dopo un'infiltrazione",
    "Realizzare una scala esterna in pietra",
    "Costruire un piccolo edificio accessorio in giardino",
    "Riparare una copertura in tegole danneggiata",
    "Realizzare l'isolamento a cappotto di un'intera facciata",
    "Costruire una piscina interrata (progetto complesso)",
    "Ristrutturare completamente una cucina in muratura",
    "Realizzare fondamenta per una piccola struttura",
    "Costruire una piscina interrata rivestita in mosaico",
    "Realizzare una copertura in tegole fotovoltaiche",
    "Costruire una veranda in muratura con vetrate",
    "Ristrutturare completamente una facciata condominiale (parte propria)",
    "Realizzare una scala interna in cemento armato",
    "Costruire un garage interrato",
    "Realizzare un sistema di drenaggio perimetrale per fondazioni",
    "Costruire una cantina interrata per vini",
    "Realizzare un pavimento industriale in resina per garage",
    "Costruire un muro di contenimento per un terreno in pendenza",
    "Realizzare un tetto verde (giardino pensile)",
    "Costruire una piscina naturale biologica",
    "Ristrutturare un sottotetto trasformandolo in mansarda abitabile",
    "Realizzare un impianto di riscaldamento a pavimento",
    "Costruire una casetta da giardino in muratura completa",
    "Realizzare un sistema di isolamento acustico tra piani",
    "Costruire un ampliamento in muratura di una stanza esistente",
    "Realizzare una cisterna interrata per l'acqua piovana",
    "Costruire una scala esterna antincendio in cemento",
    "Ristrutturare completamente un bagno con nuova disposizione sanitari"
  ],
  "mobili": [
    "Montare un armadio componibile",
    "Montare una scrivania",
    "Montare una libreria",
    "Montare un letto con rete a doghe",
    "Montare una cabina armadio componibile",
    "Montare una cucina componibile base",
    "Montare uno scaffale da garage",
    "Fissare una TV a muro con staffa",
    "Montare una scarpiera",
    "Montare una cassettiera",
    "Montare un mobiletto porta-TV",
    "Montare una specchiera da bagno",
    "Montare un letto a soppalco",
    "Montare una cuccia per animali componibile",
    "Montare un tavolo allungabile",
    "Montare una cucina componibile completa con elettrodomestici",
    "Montare un armadio a muro su misura",
    "Assemblare una scrivania ergonomica regolabile in altezza",
    "Montare un letto contenitore",
    "Montare una parete attrezzata componibile",
    "Assemblare mobili per un intero soggiorno",
    "Montare un mobile bagno sospeso con lavabo",
    "Montare una cabina armadio con luci integrate",
    "Assemblare una cucina componibile ad angolo",
    "Montare un sistema di scaffalature modulari da magazzino",
    "Montare una consolle da ingresso",
    "Montare un letto a castello",
    "Montare un mobile porta-scarpe con panca",
    "Montare una libreria a giorno componibile",
    "Montare un mobile bar componibile",
    "Montare un guardaroba estraibile",
    "Montare un mobile lavanderia componibile",
    "Montare un espositore componibile per negozio",
    "Montare una scrivania ad angolo per ufficio",
    "Montare un armadio con ante a specchio",
    "Montare un letto imbottito con contenitore",
    "Montare una cucina componibile lineare grande",
    "Montare un mobile TV sospeso a parete",
    "Montare un vano guardaroba walk-in completo",
    "Montare arredi componibili per un ufficio intero",
    "Montare un mobile bagno doppio lavabo",
    "Montare una cabina armadio a L componibile",
    "Montare un sistema di mensole modulari per negozio",
    "Montare una cucina componibile con isola centrale",
    "Montare un intero arredamento camera da letto",
    "Montare un mobile porta-stampante per ufficio",
    "Montare una cassapanca portaoggetti",
    "Montare un mobile per la lavanderia con cesti estraibili",
    "Montare uno scaffale industriale per magazzino",
    "Montare un mobile ingresso con appendiabiti integrato",
    "Montare un letto trasformabile a scomparsa (letto a muro)",
    "Montare arredi per una cameretta bambini completa",
    "Montare un mobile porta-attrezzature audio/video",
    "Montare un sistema di ante scorrevoli per armadio a muro",
    "Montare arredi componibili per una mansarda",
    "Montare un bancone bar componibile per casa",
    "Montare un intero salotto componibile ad angolo",
    "Montare un mobile contenitore multiuso per garage",
    "Montare arredi per uno studio/ufficio in casa completo",
    "Montare una cabina armadio ad angolo su misura",
    "Montare un mobile porta-TV con vano cavi nascosti",
    "Montare arredi per un negozio con espositori a muro",
    "Montare un mobile bagno con doppio cassettone",
    "Montare una parete libreria a tutta altezza",
    "Montare un intero set camera da letto matrimoniale",
    "Montare un mobile porta-vini a muro",
    "Montare un set di comodini abbinati al letto",
    "Montare un mobile lavabo con specchio integrato",
    "Montare arredi per un angolo studio compatto",
    "Montare uno scaffale a scala decorativo",
    "Montare un mobile porta-scarpe verticale salvaspazio",
    "Montare un armadio blindato o corazzato",
    "Montare arredi per un bar/tavola calda componibili",
    "Montare un intero arredo cucina con isola e penisola",
    "Montare arredi modulari per una palestra domestica",
    "Montare un mobile contenitore sottoscala su misura",
    "Montare un sistema letto-armadio salvaspazio (letto Murphy)",
    "Montare arredi per una reception di un piccolo studio",
    "Montare un guardaroba a vista con struttura in metallo e legno",
    "Montare un intero arredamento per un monolocale",
    "Montare un mobile porta-attrezzi da officina componibile",
    "Montare una cabina armadio a isola centrale",
    "Montare un intero negozio con scaffalature a muro e isola",
    "Montare una cucina componibile con dispensa a colonna",
    "Montare un ufficio open space con postazioni modulari",
    "Montare un mobile bar da giardino componibile",
    "Montare un letto matrimoniale con testiera imbottita su misura",
    "Montare un intero showroom espositivo componibile",
    "Montare una palestra domestica con arredi modulari",
    "Montare un mobile da studio fotografico componibile",
    "Montare un intero salone di bellezza con postazioni componibili",
    "Montare una cabina prova componibile per un negozio",
    "Montare un intero magazzino con scaffalature industriali",
    "Montare arredi componibili per una sala conferenze",
    "Montare un mobile bar completo con cantinetta vino integrata",
    "Montare un mobile porta-scarpe estraibile salvaspazio",
    "Montare una parete divisoria con libreria integrata",
    "Montare un ripostiglio componibile in mansarda",
    "Montare un mobile bagno con lavabo doppio e specchi retroilluminati",
    "Montare un intero atelier di sartoria con arredi su misura"
  ],
  "giardinaggio": [
    "Piantare un prato da zero",
    "Potare una siepe",
    "Installare un impianto di irrigazione goccia a goccia",
    "Costruire una piccola aiuola rialzata",
    "Trattare le piante da malattie fungine comuni",
    "Installare un impianto di illuminazione da giardino a basso voltaggio",
    "Rinvasare una pianta",
    "Costruire un compostaggio fai-da-te",
    "Installare una grondaia per la raccolta acqua piovana",
    "Montare un gazebo da giardino",
    "Costruire un orto rialzato",
    "Installare una rete paravento",
    "Piantare siepi da confine",
    "Trattare il prato dalle erbacce",
    "Installare un timer per l'irrigazione automatica",
    "Costruire un piccolo laghetto da giardino",
    "Installare un sistema di irrigazione a pioggia per il prato",
    "Costruire una serra da giardino",
    "Realizzare un vialetto in ghiaia o pietra",
    "Costruire una pergola in legno per rampicanti",
    "Installare pannelli solari da giardino per illuminazione",
    "Progettare e realizzare un giardino roccioso",
    "Costruire una recinzione perimetrale completa",
    "Installare un sistema di irrigazione automatico con centralina",
    "Realizzare un impianto di drenaggio per un giardino allagato",
    "Piantare alberi da frutto in giardino",
    "Costruire un pergolato metallico con base in cemento",
    "Realizzare un prato sintetico da giardino",
    "Installare fioriere autoirriganti da balcone",
    "Costruire una casetta da attrezzi in giardino",
    "Realizzare un percorso pedonale in pietra naturale",
    "Installare una centralina di irrigazione smart",
    "Costruire un muretto per aiuola rialzata in pietra",
    "Realizzare un giardino verticale su parete",
    "Installare un impianto di illuminazione a energia solare",
    "Costruire una piscina fuori terra con base",
    "Realizzare un sistema di compostaggio a due vasche",
    "Piantare una siepe da frutto per confine",
    "Costruire una voliera da giardino",
    "Realizzare un impianto di irrigazione interrato completo",
    "Installare grondaie e pluviali su una tettoia da giardino",
    "Costruire un pollaio da giardino",
    "Realizzare terrazzamenti su un giardino in pendenza",
    "Installare un sistema di illuminazione decorativa per alberi",
    "Costruire una zona barbecue attrezzata in giardino",
    "Realizzare un orto sinergico rialzato",
    "Costruire una capanna in legno per attrezzi da giardino",
    "Installare un sistema anti-zanzare da giardino",
    "Realizzare un prato in rotoli (zolle pronte)",
    "Costruire una struttura per orto verticale idroponico",
    "Installare reti ombreggianti per il giardino",
    "Realizzare bordure decorative con pietre naturali",
    "Costruire un ricovero invernale per piante delicate",
    "Installare un sistema di nebulizzazione per terrazza",
    "Realizzare un giardino roccioso con piante grasse",
    "Costruire una serra fredda per semenzai",
    "Installare grondaie decorative in rame per il giardino",
    "Realizzare un percorso illuminato nel giardino",
    "Costruire un piccolo ponte decorativo su un laghetto",
    "Installare un sistema di raccolta e filtraggio acqua per irrigazione",
    "Realizzare una staccionata decorativa in legno",
    "Costruire fioriere sospese per balcone",
    "Installare tende a vela ombreggianti da giardino",
    "Realizzare un sentiero in traversine di legno",
    "Costruire una struttura per orto rialzato con copertura",
    "Installare un sistema di compostaggio con vermi (vermicompostaggio)",
    "Realizzare una zona relax con amache e pergolato",
    "Costruire fioriere in muratura per il terrazzo",
    "Installare grondaie con filtro foglie per il giardino",
    "Realizzare un giardino a basso consumo d'acqua (xeriscaping)",
    "Costruire una tettoia leggera per l'orto",
    "Installare un impianto di irrigazione a subirrigazione",
    "Realizzare bordure in legno per i vialetti del giardino",
    "Costruire una struttura per rampicanti sul balcone",
    "Installare protezioni invernali per l'impianto di irrigazione",
    "Realizzare un giardino zen in miniatura",
    "Costruire una casetta per insetti impollinatori",
    "Installare un impianto di irrigazione a energia solare",
    "Realizzare un orto pensile sul tetto",
    "Costruire una vasca idroponica per ortaggi",
    "Realizzare un giardino mediterraneo a bassa manutenzione",
    "Costruire una serra riscaldata per coltivazioni invernali",
    "Realizzare un impianto di fitodepurazione per acque grigie",
    "Costruire una piscina naturale con filtrazione biologica",
    "Realizzare un giardino sensoriale per non vedenti",
    "Costruire una struttura per orticoltura verticale su balcone",
    "Realizzare un frutteto con impianto di irrigazione dedicato",
    "Costruire una zona pic-nic attrezzata in giardino",
    "Realizzare un giardino d'inverno vetrato",
    "Costruire un sistema di raccolta e riciclo dell'acqua da irrigazione",
    "Realizzare un labirinto vegetale decorativo",
    "Costruire una voliera da giardino di grandi dimensioni",
    "Realizzare un giardino roccioso alpino con piante specifiche",
    "Costruire un sistema di illuminazione paesaggistica avanzato",
    "Realizzare un orto didattico per bambini",
    "Realizzare un vigneto domestico con struttura a pergola",
    "Costruire un impianto di apicoltura da giardino",
    "Realizzare un giardino tropicale in serra riscaldata",
    "Costruire una zona relax con vasca idromassaggio da esterno",
    "Realizzare un giardino commestibile con erbe aromatiche e ortaggi misti"
  ],
  "hobby": [
    "Creare un gioiello con la resina epossidica",
    "Restaurare una sedia in legno vintage",
    "Cucire un semplice cuscino",
    "Costruire una cornice per foto fai-da-te",
    "Dipingere un mobile con la tecnica shabby chic",
    "Creare candele artigianali",
    "Fare un terrario in vetro",
    "Creare un porta-chiavi da parete",
    "Rilegare un piccolo quaderno a mano",
    "Costruire una mangiatoia per uccellini",
    "Realizzare un decoupage su legno",
    "Creare un quadro con pittura acrilica fluida",
    "Costruire una casetta per uccelli in legno",
    "Cucire una borsa di stoffa semplice",
    "Creare un mosaico decorativo",
    "Realizzare gioielli in filo di rame e perline",
    "Costruire un piccolo presepe in legno",
    "Creare saponi artigianali naturali",
    "Realizzare un album fotografico scrapbooking",
    "Costruire un modellino in legno di una barca",
    "Creare bigiotteria con resina e fiori secchi",
    "Restaurare completamente un vecchio baule",
    "Costruire un diorama dettagliato",
    "Realizzare un intaglio artistico su legno",
    "Creare una collezione di mobili in miniatura",
    "Creare bracciali con nodi macramè",
    "Costruire un acquario tematico decorato",
    "Realizzare un quadro con tecnica pirografia su legno",
    "Creare accessori in feltro cucito a mano",
    "Costruire un piccolo robot con kit elettronico",
    "Realizzare stampe artigianali con linoleografia",
    "Creare gioielli con la tecnica del wire wrapping",
    "Costruire un plastico ferroviario in miniatura",
    "Realizzare ceramiche dipinte a mano",
    "Creare un erbario decorativo da parete",
    "Costruire una libreria di modellini in scala",
    "Realizzare candele scolpite artigianali",
    "Creare bigiotteria con perline di vetro di Murano",
    "Costruire una teca espositiva per collezioni",
    "Realizzare un quadro botanico con fiori pressati",
    "Creare un set di coltelli da cucina personalizzati",
    "Costruire una piccola forgia per lavorazione metalli hobbistica",
    "Realizzare intagli su sapone decorativo",
    "Creare un diorama storico dettagliato",
    "Costruire un modellino di aereo radiocomandato",
    "Realizzare stampe artigianali con la tecnica del monotipo",
    "Costruire un piccolo tornio per lavorare il legno hobbistico",
    "Creare gioielli con la tecnica della cera persa",
    "Realizzare un presepe artistico dettagliato",
    "Costruire un modellino di casa in miniatura completo",
    "Creare tappeti intrecciati a mano",
    "Realizzare quadri con la tecnica del pointillisme",
    "Costruire una collezione di soldatini dipinti a mano",
    "Creare gioielli in argento con tecniche base di oreficeria",
    "Realizzare un plastico di un paesaggio storico",
    "Costruire strumenti musicali semplici fai-da-te",
    "Creare bigiotteria ispirata a stili etnici",
    "Realizzare sculture in filo di ferro",
    "Costruire scenografie in miniatura per fotografia",
    "Creare una collezione di ceramiche raku",
    "Creare accessori in pelle cuciti a mano",
    "Realizzare un quadro con la tecnica del collage",
    "Costruire una piccola pressa per fiori essiccati",
    "Creare gioielli in filo di alluminio colorato",
    "Realizzare un libro pop-up artigianale",
    "Costruire un modellino di veliero in scala",
    "Creare decorazioni natalizie artigianali",
    "Realizzare un mosaico in vetro colorato per finestra",
    "Costruire una collezione di aquiloni decorativi",
    "Creare bigiotteria con tecnica quilling (carta arrotolata)",
    "Realizzare sculture in das o pasta di sale",
    "Costruire un piccolo carillon musicale",
    "Creare tele dipinte con la tecnica dello spray painting",
    "Realizzare bomboniere artigianali personalizzate",
    "Costruire un espositore da collezione per action figure",
    "Creare una collezione di orologi da polso artigianali",
    "Realizzare un dipinto murale decorativo",
    "Costruire un plastico di un circuito automobilistico",
    "Creare gioielli con smalti a fuoco su rame",
    "Realizzare una collezione di burattini fatti a mano",
    "Creare gioielli con tecniche di smaltatura a caldo avanzate",
    "Realizzare un plastico ferroviario in scala con paesaggio completo",
    "Costruire una collezione di modellini navali storici",
    "Creare tessuti stampati a mano con tecnica batik",
    "Realizzare una collezione di maschere artigianali",
    "Costruire un teatrino di burattini completo",
    "Creare gioielli in titanio anodizzato colorato",
    "Realizzare un erbario scientifico con classificazione botanica",
    "Costruire una collezione di strumenti musicali etnici",
    "Creare opere in vetro soffiato hobbistico",
    "Realizzare una collezione di miniature storiche in scala",
    "Costruire un plastico di una città in miniatura",
    "Creare gioielli con tecnica di filigrana",
    "Realizzare una collezione di ceramiche invetriate",
    "Costruire strumenti di precisione in legno e metallo",
    "Creare una collezione di orologi da taschino restaurati",
    "Realizzare sculture in metallo con saldatura ad arco hobbistica",
    "Costruire un planetario in miniatura funzionante",
    "Creare tessuti ricamati con tecniche tradizionali",
    "Realizzare una collezione completa di modellismo statico militare"
  ]
};
